language: python
python:
  - 3.6
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - coverage run --source=mixsig setup.py test
after_success:
  - coveralls